project:
  type: book

book:
  title: "Best Practices for Spatial Transcriptomics Analysis with Bioconductor"
  date: today
  sidebar:
    title: "Best Practices ST"
    style: docked
  search: true
  repo-url: https://github.com/lmweber/BestPracticesST
  cover-image: Bioconductor-rh.png
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - chapters/introduction.qmd
        - chapters/spatial_transcriptomics.qmd
        - chapters/bioconductor-data-classes.qmd
    - part: "Analysis steps"
      chapters:
        - chapters/analysis_steps.qmd
        - chapters/quality_control.qmd
        - chapters/normalization.qmd
        - chapters/feature_selection.qmd
        - chapters/dimensionality_reduction.qmd
        - chapters/clustering.qmd
        - chapters/spot_deconvolution.qmd
        - chapters/spatial_registration.qmd
        - chapters/differential_expression.qmd
    - part: "Workflows"
      chapters:
        - chapters/workflows.qmd
        - chapters/workflow_Visium_humanDLPFC.qmd
        - chapters/workflow_Visium_mouseCoronal.qmd
        - chapters/workflow_Visium_spatialLIBD.qmd
  appendices:
    - chapters/related_resources.qmd
    - chapters/contributors.qmd
    - chapters/references.qmd

number-sections: true

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
