project:
  type: book

book:
  title: "Best Practices for Spatial Transcriptomics Analysis with Bioconductor"
  date: today
  sidebar:
    title: "Best Practices ST"
    style: docked
  search: true
  repo-url: https://github.com/lmweber/BestPracticesST
  cover-image: Bioconductor-rh.png
  chapters:
    - index.qmd
    - part: "Introduction"
      chapters:
        - chapters/introduction.qmd
        - chapters/spatial-transcriptomics.qmd
        - chapters/bioconductor-data-classes.qmd
    - part: "Analysis steps"
      chapters:
        - chapters/analysis-steps.qmd
        - chapters/load-data.qmd
        - chapters/quality-control.qmd
        - chapters/normalization.qmd
        - chapters/feature-selection.qmd
        - chapters/dimensionality-reduction.qmd
        - chapters/clustering.qmd
        - chapters/spot-deconvolution.qmd
        - chapters/spatial-registration.qmd
        - chapters/differential-expression.qmd
        - chapters/multiple-samples.qmd
        - chapters/spatial-co-localization.qmd
    - part: "Workflows"
      chapters:
        - chapters/workflows.qmd
        - chapters/workflow-Visium-humanDLPFC.qmd
        - chapters/workflow-Visium-mouseCoronal.qmd
        - chapters/workflow-Visium-spatialLIBD.qmd
  appendices:
    - chapters/related-resources.qmd
    - chapters/acknowledgments.qmd
    - chapters/references.qmd

number-sections: true

bibliography: references.bib

execute:
  freeze: auto

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
